services:
  postgres:
    image: postgres:16-alpine
    container_name: kratom-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kratom
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kratom"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - kratom-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kratom-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      # Database connection string
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/kratom
      - DRIZZLE_DATABASE_URL=postgres://postgres:postgres@postgres:5432/kratom
      # Individual database connection parameters for fallback
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=kratom
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      # Other settings
      - PORT=5000
      - LOG_LEVEL=debug
      - SESSION_SECRET=replace_this_with_a_long_secure_random_string_in_production
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - kratom-network

volumes:
  postgres-data:
    driver: local

networks:
  kratom-network:
    driver: bridge
